### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by PygmalionChen** [senya-ashukha/quantile-regression-dqn-pytorch#1]
Firstly, I run the rl_utils.py and it generate a qr-dqn-solution-cool.ipynb file.
When I try to run the code in ipython notebook, the following error occured. Is there something wrong?

    self.print = prin
             ^
SyntaxError: invalid syntax

**Comment by senya-ashukha** [comment]
Hi,

Thanks for the reporting. I reproduce it with python 2 bit the repo is comparable with python 3.
